# Generated by Django 5.1.2 on 2024-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(choices=[('work', 'Work'), ('office', 'Office'), ('home', 'Home'), ('business', 'Business'), ('family', 'Family')], default='work', max_length=10)),
            ],
        ),
    ]
